# Generated by Django 6.1 on 2026-08-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.CharField(default='Dashain Cup 2026', max_length=120)),
                ('division', models.CharField(default='Open 7A-side football competition', max_length=160)),
                ('team_name', models.CharField(max_length=120)),
                ('manager_name', models.CharField(max_length=120, verbose_name='Manager / Coach name')),
                ('home_city', models.CharField(max_length=120, verbose_name='Home city / suburb')),
                ('phone', models.CharField(max_length=40)),
                ('gmail', models.EmailField(max_length=254, verbose_name='Team Gmail address')),
                ('squad_size', models.CharField(blank=True, choices=[('', 'Select squad size'), ('7-9', '7 – 9 players'), ('10-12', '10 – 12 players'), ('13-15', '13 – 15 players'), ('16+', '16+ players')], max_length=10)),
                ('experience', models.TextField(blank=True, default='', verbose_name='Previous tournament experience')),
                ('notes', models.TextField(blank=True, default='')),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('organiser_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team registration',
                'verbose_name_plural': 'Team registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
