# Generated by Django 6.1 on 2026-08-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamregistration',
            name='pin_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='players',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='teamregistration',
            name='home_city',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Home city / suburb'),
        ),
        migrations.AlterField(
            model_name='teamregistration',
            name='manager_name',
            field=models.CharField(max_length=120, verbose_name='Captain name'),
        ),
    ]
