# Generated by Django 6.1.1 on 2026-09-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_squad_pin_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamregistration',
            name='logo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='logo_content_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='logo_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
