# Generated by Django 6.1.1

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_team_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamregistration",
            name="payment_received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teamregistration",
            name="payment_receipt",
            field=models.BinaryField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="teamregistration",
            name="payment_receipt_content_type",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="teamregistration",
            name="payment_receipt_filename",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="teamregistration",
            name="payment_token",
            field=models.CharField(
                default=registration.models.generate_payment_token,
                editable=False,
                max_length=64,
                unique=True,
            ),
        ),
    ]
