# Generated by Django 6.1.1

from django.db import migrations, models

import registration.models


def backfill_payment_tokens(apps, schema_editor):
    """Give every existing team its own token before the unique constraint is added.

    SQLite applies a field default once when rebuilding the table, so a unique
    default on AddField would duplicate the same token across existing rows.
    """
    TeamRegistration = apps.get_model("registration", "TeamRegistration")
    used = set(
        TeamRegistration.objects.exclude(payment_token="").values_list(
            "payment_token", flat=True
        )
    )
    for team in TeamRegistration.objects.all().iterator():
        if team.payment_token and team.payment_token not in ("", None):
            used.add(team.payment_token)
            continue
        token = registration.models.generate_payment_token()
        while token in used:
            token = registration.models.generate_payment_token()
        team.payment_token = token
        team.save(update_fields=["payment_token"])
        used.add(token)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_team_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamregistration",
            name="payment_received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teamregistration",
            name="payment_receipt",
            field=models.BinaryField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="teamregistration",
            name="payment_receipt_content_type",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="teamregistration",
            name="payment_receipt_filename",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="teamregistration",
            name="payment_token",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=64,
            ),
        ),
        migrations.RunPython(backfill_payment_tokens, noop),
        migrations.AlterField(
            model_name="teamregistration",
            name="payment_token",
            field=models.CharField(
                default=registration.models.generate_payment_token,
                editable=False,
                max_length=64,
                unique=True,
            ),
        ),
    ]
